### ISSUE TITLE
Ace Options 

### ISSUE THREAD

**Issue by ProjectAwesomeGaming** [ProjectAwesomeGaming/Community-Feedback#11]
no ace options in the top left corner of the esc menu

**Comment by ProjectAwesomeGaming** [comment]
This is a message I copied over from the Test-Repo issue tracker. The original issue was brought up by Foodstamp. I believe you can access the ace options in "addon options" in the normal ARMA menu now but we should check to be sure.

**Comment by Hamster2k** [comment]
https://ace3mod.com/2017/12/20/cba-settings.html
