### ISSUE TITLE
Ace goggles

### ISSUE THREAD

**Issue by ProjectAwesomeGaming** [ProjectAwesomeGaming/Community-Feedback#12]
Dirt on goggles is OK, Night vision is terrible, not playable

**Comment by ProjectAwesomeGaming** [comment]
This is a message I copied over from the Test-Repo issue tracker. The original issue was brought up by Foodstamp.

**Comment by ProjectAwesomeGaming** [comment]
It seems the night vision issue might be from ace_nightvision -Foodstamp

Could be from @enhancedmovement -Jonas

https://project-awesome.slack.com/files/U5QE71PRS/F8RRVNS12/image.png

Whatever it is it needs to be removed. I don't know where the dirt comes from. I think it might be from a goggles.pbo that we removed from the last version of ACE.

**Comment by linkspec** [comment]
File patching has been added, can this be closed?

**Comment by Hamster2k** [comment]
It works now!
