### ISSUE TITLE
Add -filePatching to startup parameters for the test repo

### ISSUE THREAD

**Issue by Hamster2k** [ProjectAwesomeGaming/Community-Feedback#14]
The parameter allows the userconfig we created for the server to modify user settings.

**Comment by Hamster2k** [comment]
This is supposed to fix #12  and #13 together with the server config I uploaded.

**Comment by Hamster2k** [comment]
What the parameter does is explained here: https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#userconfig

**Comment by linkspec** [comment]
Unless I'm mistaken, thats going to require the users to launch with the parameter as well?

**Comment by Hamster2k** [comment]
I'm pretty sure only the server needs the parameter, as only the server is going to load the file. All clients will have their own cba settings and that is fine. If clients miss settings they will be imported from the server. The stuff we have set up to override client settings should happen when they are connected to the server. Hope that made sense!

**Comment by linkspec** [comment]
I'm may be misunderstanding here. I was under the impression that this was about putting all ace mods in the addons folder and then controlling which ones load by a config file? If that's the case, then the clients will also have all ace mods in their addons folder, but won't have the parameter set up to only load the ones from config. So, for example, they will run goggles.pbo even if the server doesn't. If someone wants to grab me on TS tonight to clarify, let me know

**Comment by Hamster2k** [comment]
They will be running googles.pbo if they don't disable it and they play on their own, but it will be disabled per config on our server. The server enforces this behaviour on all connecting clients.

The complete ACE mod is being loaded, but parts of it are disabled in the settings. There's basically three levels of settings you can do. Server settings, client settings, mission settings (and then there's placed editor modules). Per default all client and mission settings override server settings, but you can set it up in the config so parts of the server config (goggles for example) can't be overridden by mission or client.

I'm pretty sure it works like this, but even if it doesn't, why can't we just go ahead and test it?

**Comment by linkspec** [comment]
I have no objection to testing it now I understand the expected behaviour. However, last I checked, wheat had some reservations - if he gives me the green light, I'll add it.

**Comment by linkspec** [comment]
Complete
