### ISSUE TITLE
Swap Acepa with full Ace

### ISSUE THREAD

**Issue by Hamster2k** [ProjectAwesomeGaming/Community-Feedback#15]
Call it @ace so Swifty discovers the mod if it's already available on the client.

The userconfig (provided it works #14 ) should cover all our bases!

I recommend we wait until we've tested the user config once and then do the swap.

**Comment by ProjectAwesomeGaming** [comment]
When you say "swap" do you mean swapping acepa with ace or test repo to main?

**Comment by Hamster2k** [comment]
I mean removing Acepa and adding Ace to the test repo.

**Comment by Hamster2k** [comment]
Thanks wheat!
