### ISSUE TITLE
What happens if Link get's hit by a bus?

### ISSUE THREAD

**Issue by ProjectAwesomeGaming** [ProjectAwesomeGaming/Community-Feedback#19]
See group chat with Wheat, Klausman, Hamster and Link in Discord.

**Comment by linkspec** [comment]
Link goes squish - links (drunk) wife

**Comment by ProjectAwesomeGaming** [comment]
RIP Link. You will be missed.

**Comment by linkspec** [comment]
Ok, didn't actually died, so I am working on documentation to enable others to take over should it be needed.

**Comment by linkspec** [comment]
First draft now located in the google drive folder

**Comment by linkspec** [comment]
This is now being managed within the drive document, so closing this ticket.
