### ISSUE TITLE
Names not appearing

### ISSUE THREAD

**Issue by Foodstamp001** [ProjectAwesomeGaming/Community-Feedback#30]
Player names do not appear when hovering over them.

**Comment by Hamster2k** [comment]
Needs testing with the config. Pretty sure I saw name tags, but can't 100% it off the top of my head.

**Comment by Hamster2k** [comment]
They still don't show up, even though they are configured to do so in the settings.

**Comment by ProjectAwesomeGaming** [comment]
Do we have any plans of how to deal with this?

**Comment by Hamster2k** [comment]
Fixed with new config setting!
