### ISSUE TITLE
Desync

### ISSUE THREAD

**Issue by Hamster2k** [ProjectAwesomeGaming/Community-Feedback#31]
Throughout yesterday the server had a lot of desync and people seemed to drop. A restart of the VM fixed the issue. No idea what caused it, let's leave this issue open for a while and see if it happens again.

**Comment by jonas232** [comment]
After the VM reboot, there was still desync. And temporary connection loss (red link).

**Comment by linkspec** [comment]
Netlog has revealed that packets are falling over and having to be resent. Research has not turned up any reason why it might be happening, so have opened a thread at the BI forums:
https://forums.bohemia.net/forums/topic/213452-netchannel-21-refused-a-packet/

**Comment by Foodstamp001** [comment]
I've noticed that my ping will remain constant at 17-19, but my bandwidth goes to ~80 during red/yellow chains then up to 800, then back down again. Everyone's bounces but I didn't memorize all the numbers

**Comment by linkspec** [comment]
Forgot to close this following the rebuild
