### ISSUE TITLE
RHS scopes not zeroable

### ISSUE THREAD

**Issue by Hamster2k** [ProjectAwesomeGaming/Community-Feedback#37]
Proposed fix: Enable ACE zeroing and set to simplified.

**Comment by ProjectAwesomeGaming** [comment]
How is this different than we had it on the server previously?

**Comment by Hamster2k** [comment]
https://imgur.com/h8WvjDe

Zeroing in 50m increments with the default key bindings. Fixes all RHS scopes! Deployed in the config now.
