### ISSUE TITLE
Create automated repo list

### ISSUE THREAD

**Issue by linkspec** [ProjectAwesomeGaming/Community-Feedback#4]

**Comment by ProjectAwesomeGaming** [comment]
So what is this again?

**Comment by linkspec** [comment]
This: http://swifty.projectawesome.net/repoinfo.php

Also, this is now complete - will leave ticket open for a day or so for feedback/bugs

**Comment by ProjectAwesomeGaming** [comment]
Will this update when the mods are updated? Is there no way to get the same format that the test repo gives us? 

http://swifty.projectawesome.net/testrepo/

**Comment by linkspec** [comment]
Yes it will update automatically.

I didn't say it couldn't be done, I said it shouldn't be. Exposing directory structure is bad practice which was only done as we didn't have a better alternative.
