### ISSUE TITLE
Bandwith Loss?

### ISSUE THREAD

**Issue by Foodstamp001** [ProjectAwesomeGaming/Community-Feedback#8]
Server will not progress pass "waiting for host" if there are more than a couple people downloading the test repo.

**Comment by linkspec** [comment]
Will look at adding some bandwidth monitoring

**Comment by ProjectAwesomeGaming** [comment]
Would the server monitoring that Klausman setup help with any of this?

**Comment by klausman** [comment]
Do you have a time (UTC) when this happened? Then I can take a closer look at the monitoring.

https://snapshot.raintank.io/dashboard/snapshot/W4VdcT7404VL2cxBSIv7YxtjGntywUBZ?orgId=2

We hit almost 1Gbit/s at one point last night. I don't think there's much we can do about that, short of moving the test/main repo to a different machine.

**Comment by klausman** [comment]
https://snapshot.raintank.io/dashboard/snapshot/W4VdcT7404VL2cxBSIv7YxtjGntywUBZ?orgId=2

We hit almost 1Gbit/s at one point last night. I don't think there's much we can do about that.

**Comment by linkspec** [comment]
Bandwidth limits applied to swifty machine.
