### ISSUE TITLE
Uploading mods to the repo using filezilla sometimes doesn't upload the whole file

### ISSUE THREAD

**Issue by ProjectAwesomeGaming** [ProjectAwesomeGaming/Community-Feedback#9]
After uploading files I've been checking the size compared to what I uploaded and a lot of time it's missing multiple gigs. I have no idea why it's doing this so often. Happened twice today when uploading 5 files.

**Comment by linkspec** [comment]
Are there any errors? Anything showing in the 'Failed transfers' tab of filezilla?

**Comment by ProjectAwesomeGaming** [comment]
not that i noticed

**Comment by linkspec** [comment]
Added logging to filezilla server, plz let me know if it happens again

**Comment by ProjectAwesomeGaming** [comment]
I'll be downloading the mods directly to the server from this point forward until a better option presents itself.
